name: Feature workflow

on:
  push:
    branches:
      - feature
      - bugfix/**

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build and publish with Maven
        run: |
          # Versioning setup
          version_prefix=`mvn help:evaluate -Dexpression=project.version --quiet -DforceStdout --file pom.xml | awk -F. '{print $1"."$2}'`
          version="$version_prefix.${{github.run_number}}-$GITHUB_SHA"
          echo "Setting artifact version to $version"
          # Push version to env
          echo "ARTIFACT_VERSION=$version" >> $GITHUB_ENV
          # Overwrite local artifact version
